accessControl:
  salt: zKgX43oHtyVzDz0uhpXvz9br1IF1o8Ed
api:
  key: 76869BD8452D494093FB91332240F245
appearance:
  name: TazStiff
controls:
- children:
  - command: M42 P13 S255
    name: Laser ON
  - command: M42 P13 S0
    name: Laser OFF
  layout: horizontal
  name: Laser
- children:
  - command: G0 X200 Y150 F9000
    name: Center
  - command: G0 X80 Y70 F9000
    name: TopLeft
  - command: G0 X150 Y35 F9000
    name: TopCenter
  - command: G0 X200 Y70 F9000
    name: TopRight
  - command: G0 X325 Y70 F9000
    name: BottomLeft
  - command: G0 X80 Y315 F9000
    name: BottomCenter
  - command: G0 X200 Y315 F9000
    name: BottomRight
  layout: horizontal
  name: Position
- children:
  - commands:
    - G28
    - G29 V4 T
    name: Topo
  layout: horizontal
  name: Area
- children:
  - command: M25
    name: PauseSD
  collapsed: true
  layout: horizontal
  name: Util
feature: {}
gcodeViewer: {}
plugins:
  _disabled:
  - cura
  - discovery
  - virtual_printer
  cura:
    _config_version: null
    cura_engine: /usr/local/bin/cura_engine
    debug_logging: false
    default_profile: null
  discovery:
    _config_version: null
    httpPassword: null
    httpUsername: null
    model:
      description: null
      name: null
      number: null
      serial: null
      url: null
      vendor: null
      vendorUrl: null
    pathPrefix: null
    publicHost: null
    publicPort: 80
    upnpUuid: 29a6f475-4889-42a9-b2b1-a87dd3aba7df
    zeroConf: []
  firmwareupdater:
    avrdude_path: /usr/bin/avrdude
    check_after_connect: false
  softwareupdate:
    _config_version: 4
    checks:
      octoprint:
        checkout_folder: /home/pi/OctoPrint
        type: github_release
        update_script: '{python} "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.2-py2.7.egg/octoprint/plugins/softwareupdate/scripts/update-octoprint.py"
          --python="{python}" "{folder}" {target}'
printerParameters: {}
printerProfiles:
  defaultProfile:
    axes:
      e:
        inverted: false
        speed: 65
      x:
        inverted: false
        speed: 9000
      y:
        inverted: false
        speed: 9000
      z:
        inverted: false
        speed: 200
    color: default
    extruder:
      count: 2
      nozzleDiameter: 0.4
      offsets:
      - - 0.0
        - 0.0
      - - 0.0
        - 0.0
    heatedBed: true
    id: _default
    model: TazStiff
    name: TazStiff
    volume:
      depth: 300.0
      formFactor: rectangular
      height: 200.0
      origin: lowerleft
      width: 300.0
serial:
  autoconnect: true
  baudrate: 250000
  port: /dev/serial/by-id/usb-UltiMachine__ultimachine.com__RAMBo_74031303437351C05161-if00
  timeout:
    sdStatus: 3.0
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
  firstRun: false
  secretKey: WUIAqe4FdrpOBjMch3WJvSOsIHGtzjw9
system:
  actions:
  - action: shutdown
    async: true
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    ignore: true
    name: Shutdown
  - action: reboot
    async: true
    command: sudo shutdown -r now
    confirm: You are about to reboot the system
    ignore: true
    name: Reboot
  - action: restart
    async: true
    command: sudo service octoprint restart
    confirm: You are about to restart OctoPrint
    ignore: true
    name: Restart OctoPrint
temperature:
  profiles:
  - bed: '105'
    extruder: '230'
    name: ABS
  - bed: '65'
    extruder: '185'
    name: PLA
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream
  watermark: false
